### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by sam2if** [osmanwako/Leaderboard#4]
Hi, @osmanwako Good job so far!

- kindly use async and await in every your function you created instead of callback.

-

**Comment by Christelle-12** [comment]
Hello @osmanwako ,congratulations🎉  on implementing this project 

![conngz](https://user-images.githubusercontent.com/105784335/234204737-d2862a88-a399-49b4-83e8-3986d02a5706.gif)
## Status : APPROVED 🥳 🥳 

Your project seems great!  There is nothing else to say...

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great UI ✨ 
- Implemented all requirements 👏 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
